# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.8.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /data/media:Z
    io.podman.annotations.kube.health.check/podarr-prowlarr: "true"
    io.podman.annotations.userns: keep-id
    io.podman.annotations.userns/podarr-prowlarr: keep-id
  creationTimestamp: "2026-04-15T21:47:05Z"
  labels:
    app: podarr
  name: podarr
spec:
  containers:
  - image: ghcr.io/flaresolverr/flaresolverr:latest
    name: flaresolverr
    ports:
    - containerPort: 8191
      hostPort: 8191
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
  - image: lscr.io/linuxserver/prowlarr:latest
    name: prowlarr
    ports:
    - containerPort: 9696
      hostPort: 9696
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    volumeMounts:
    - mountPath: /config
      name: prowlarr-config
  - image: lscr.io/linuxserver/bazarr:latest
    name: bazarr
    ports:
    - containerPort: 6767
      hostPort: 6767
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    volumeMounts:
    - mountPath: /config
      name: bazarr-config
    - mountPath: /data/media
      name: media
  hostUsers: false
  restartPolicy: Always
  volumes:
  # Mount Binds
  - hostPath:
      path: /data/config/prowlarr
      type: Directory
    name: prowlarr-config
  - hostPath:
      path: /data/config/bazarr
      type: Directory
    name: bazarr-config
  - hostPath:
      path: /data/media
      type: Directory
    name: media
