# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.8.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /data/media:Z
    io.containers.autoupdate/myjellyfin: registry
    io.podman.annotations.kube.health.check/podarr-jellyfin: "true"
    io.podman.annotations.kube.health.check/podarr-prowlarr: "true"
    io.podman.annotations.kube.health.check/podarr-radarr: "true"
    io.podman.annotations.kube.health.check/podarr-sonarr: "true"
    io.podman.annotations.userns: keep-id
    io.podman.annotations.userns/podarr-jellyfin: keep-id
    io.podman.annotations.userns/podarr-prowlarr: keep-id
    io.podman.annotations.userns/podarr-radarr: keep-id
    io.podman.annotations.userns/podarr-sonarr: keep-id
  creationTimestamp: "2026-04-15T21:47:05Z"
  labels:
    app: podarr
  name: podarr
spec:
  containers:
  - image: ghcr.io/flaresolverr/flaresolverr:latest
    name: flaresolverr
    ports:
    - containerPort: 8191
      hostPort: 8191
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
  - image: lscr.io/linuxserver/prowlarr:latest
    name: prowlarr
    ports:
    - containerPort: 9696
      hostPort: 9696
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    volumeMounts:
    - mountPath: /config
      name: prowlarr-config
  - image: lscr.io/linuxserver/bazarr:latest
    name: bazarr
    ports:
    - containerPort: 6767
      hostPort: 6767
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    volumeMounts:
    - mountPath: /config
      name: bazarr-config
    - mountPath: /data/media
      name: media
  - image: lscr.io/linuxserver/sonarr:latest
    name: sonarr
    ports:
    - containerPort: 8989
      hostPort: 8989
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    volumeMounts:
    - mountPath: /data
      name: data
    - mountPath: /config
      name: sonarr-config
  - image: lscr.io/linuxserver/radarr:latest
    name: radarr
    ports:
    - containerPort: 7878
      hostPort: 7878
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    volumeMounts:
    - mountPath: /data
      name: data
    - mountPath: /config
      name: radar-config
  - image: docker.io/jellyfin/jellyfin:latest
    name: jellyfin
    ports:
    - containerPort: 8096
      hostPort: 8096
    securityContext:
      runAsGroup: 992
      runAsUser: 1000
    volumeMounts:
    - mountPath: /media
      name: media
      readonly: true
    - mountPath: /config
      name: jellyfin-config
    - mountPath: /cache
      name: jellyfin-cache-pvc
    - mountPath: /dev/dri/renderD128
      name: VA-API
      readonly: true
  hostUsers: false
  restartPolicy: Always
  volumes:
  # Mount Binds
  - hostPath:
      path: /data
      type: Directory
    name: data
  - hostPath:
      path: /data/media
      type: Directory
    name: media
  - hostPath:
      path: /data/config/prowlarr
      type: Directory
    name: prowlarr-config
  - hostPath:
      path: /data/config/bazarr
      type: Directory
    name: bazarr-config
  - hostPath:
      path: /data/config/sonarr
      type: Directory
    name: sonarr-config
  - hostPath:
      path: /data/config/radarr
      type: Directory
    name: radar-config
  - hostPath:
      path: /data/config/jellyfin
      type: Directory
    name: jellyfin-config
  - hostPath:
      path: /dev/dri/renderD128
      type: Directory
    name: VA-API
  # Virtual Volumes
  - name: jellyfin-cache-pvc
    persistentVolumeClaim:
      claimName: jellyfin-cache
